source/Components/Xceed.Wpf.AvalonDock/Controls/LayoutAnchorableFloatingWindowControl.cs
source/Components/Xceed.Wpf.AvalonDock/DockingManager.cs

In our application when we change the theme we have to reload the application layout. If we have a visible floating window after the theme change we have the following exceptions:
**MyApp.Common.Exceptions.BindingException: System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='<null>' BindingExpression:Path=; DataItem=null; target element is 'LayoutAnchorableFloatingWindowControl' (Name=''); target property is 'Visibility' (type 'Visibility')**
at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
at MS.Internal.AvTrace.Trace(TraceEventType type, Int32 eventId, String message, String[] labels, Object[] parameters)
at MS.Internal.TraceData.Trace(TraceEventType type, …

Fix Visibility issues in LayoutFloatingWindowControl

---

source/Components/Xceed.Wpf.AvalonDock/Controls/LayoutFloatingWindowControl.cs

The Issue is similar to one which we fixed with https://github.com/Dirkster99/AvalonDock/pull/36/files#diff-a23d38de9c85b74a8efe7ef17b582374L2403
The only difference is that at first time of Close of floating window called not from InternalClose but by handling WindowMessage.WM_CLOSE in System.Windows.Window.cs
It has the same call stack:
System.InvalidOperationException: Cannot set Visibility to Visible or call Show, 
ShowDialog, Close, or WindowInteropHelper.EnsureHandle while a Window is closing.
at System.Windows.Window.VerifyNotClosing()
at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
at Xceed.Wpf.AvalonDock.DockingManager.DockingManager_Unloaded(Object sender, 
RoutedEventArgs e)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, …

Fix Visibility issue on closing LayoutFloatingWindowControl

---

source/Components/Xceed.Wpf.AvalonDock/Controls/FocusElementManager.cs

For resolve issue "System.InvalidOperationException: Cannot perform this operation while dispatcher processing is suspended." make async subscribing instead of sync subscribing.

#42 Fix Dispatcher Suspend Exception issue

---

source/Components/Xceed.Wpf.AvalonDock/Controls/LayoutGridControl.cs

Here some improvement for calculation of available size in AdjustFixedChildrenPanelSizes method. This will allow to calculate panelFraction value according to available size. As result when we decrease root panel, the children panel will decreasing synchronously.

Improvement for calculation of available size

---

source/Components/Xceed.Wpf.AvalonDock/Controls/LayoutGridControl.cs
source/Components/Xceed.Wpf.AvalonDock/Controls/LayoutPanelControl.cs
source/Components/Xceed.Wpf.AvalonDock/Layout/ILayoutPositionableElement.cs
source/Components/Xceed.Wpf.AvalonDock/Layout/LayoutPositionableGroup.cs

This fix for calculating of DockMinSizes based on children minimal dimensions.
For cases when we have some complex structure, like this:
```
Group Panel (horizontal):
Anchorable Panel # 1 (DockMinWidth = 150) "File Stats";
Group Panel (vertical):
Anchorable Panel # 2 (DockMinWidht = 150) "Tool1";
Anchorable Panel # 3 (DockMinWidht = 150) "Color Picker";
```
When we decreasing width of horizontal Group Panel it's not take into account of DockMinWidth for panels # 2 and # 3. And these panels becomes partly hidden under Document panel (see attached screenshot)

Made calculating of DockMinSize for panel based on children DockMinSize

---

source/AutomationTest/Xceed.Wpf.AvalonDock.Test/DockingUtilitiesTest.cs
source/AutomationTest/Xceed.Wpf.AvalonDock.Test/LayoutAnchorableTest.cs
source/AutomationTest/Xceed.Wpf.AvalonDock.Test/Xceed.Wpf.AvalonDock.Test.csproj
source/Components/Xceed.Wpf.AvalonDock/Controls/LayoutAnchorableFloatingWindowControl.cs
source/Components/Xceed.Wpf.AvalonDock/Controls/LayoutAnchorableItem.cs
source/Components/Xceed.Wpf.AvalonDock/Controls/LayoutFloatingWindowControl.cs
source/Components/Xceed.Wpf.AvalonDock/Controls/LayoutGridControl.cs
source/Components/Xceed.Wpf.AvalonDock/DockingManager.cs
source/Components/Xceed.Wpf.AvalonDock/Layout/LayoutAnchorable.cs

Fixed two issues:
1) Undocked panel doesn't show after switching between tabs.
2) Undocked panel doesn't hide the first time it's unchecked from the main menu, while hiding/showing on the next attempts.
LayoutAnchorableFloatingWindowControl.cs
Added restoring of visibility binding on "activated" event.
Added possibility to disable/enable visibility bindings when docking manager gets unloaded ("unloaded" fires when switching between tabls).
DockingManager.cs
When "unloaded" fires, instead of closing all floating controls and creating them again when "loaded" fires, we transfer them to the list of hidden controls disabling their visibility bindings and event subscriptions. This solves issue 1).
LayoutAnchorableItem.cs
Added separate visibility reentrant flag for "LayoutAnchorable …

Fix visibility bindings of undocked panels in specific cases

---

source/Components/Xceed.Wpf.AvalonDock/Controls/NavigatorWindow.cs

The current logic in the Ctrl-Tab processing in the Navigator window expects there to be a mixture of both LayoutAnchorables and LayoutDocuments. But if you only have a list of one or the other type the Ctrl-Tab selection does not loop to the top of the list, it stays stuck on the last item as it is expecting to jump across to the other list (you can see this behaviour in MLibTest app which only has LayoutAnchorables, once you ctrl-tab to the bottom of the list the blue highlight stays stuck there and that last Anchorable will get focus once you release the ctrl-tab. (note you need to keep the ctrl key held down and tap on the tab key to cycle the selected item)
This pull request adds a check in each set of conditions so that the selected item will loop to the top of the current list …

Repeatedly pressing Ctrl-Tab gets stuck at the bottom of the list of LayoutItems

---

source/AutomationTest/Xceed.Wpf.AvalonDock.Test/LayoutAnchorableFloatingWindowControlTest.cs
source/AutomationTest/Xceed.Wpf.AvalonDock.Test/Views/LayoutAnchorableFloatingWindowControlTestWindow.xaml
source/AutomationTest/Xceed.Wpf.AvalonDock.Test/Views/LayoutAnchorableFloatingWindowControlTestWindow.xaml.cs
source/AutomationTest/Xceed.Wpf.AvalonDock.Test/Xceed.Wpf.AvalonDock.Test.csproj
source/Components/Xceed.Wpf.AvalonDock/DockingManager.cs

Hello, 
I've seen LayoutAnchorableFloatingWindowControl.OnClosed() crash because of root.Manager is null for the hidden LayoutFloatingWindowControl:
root.Manager.RemoveFloatingWindow( this );
Please, take a look to the proposed PR that clears list of hidden floating windows

74 The old NullReferenceException comes back

---

source/Components/AvalonDock/DockingManager.cs
source/Components/AvalonDock/Layout/LayoutRoot.cs

Fixed issue that an empty frame is left behind. Also fixes issue that in the main window a document group panel was deleted when no documents were present.

Fix for bug 112, Closing documents leaves empty frame.

---

source/Components/AvalonDock/Controls/LayoutAnchorablePaneControl.cs
source/Components/AvalonDock/Controls/LayoutDocumentPaneControl.cs
source/Components/AvalonDock/TabControlEx.cs

LayoutDocumentPaneControl and LayoutAnchorablePaneControl were derived from regular WPF TabControl. I replaced it with TabControlEx which supports virtualization of tab controls to increase performance. See issue #142 for more details.
TODO: Someone may not like this behavior. An option should be added at `DockingManager` level or as a property of `LayoutAnchorable` so it retains original behavior (documents are unloaded/loaded when "tabs"/documents are changed.

Replaced TabControl with TabControlEx

---

.gitignore
source/AvalonDocPanelMemoryLeaks/MainWindow.xaml
source/Components/AvalonDock/Controls/LayoutDocumentControl.cs
source/Components/AvalonDock/Layout/LayoutGroup.cs
source/MLibTest/MLibTest/AvalonDock.Layout.config

change override void OnPreviewGotKeyboardFocus to OnPreviewMouseLeftButtonUp

Fix doc isActive problem

---

source/AutomationTest/AvalonDockTest/AnchorablePaneTest.cs
source/AutomationTest/AvalonDockTest/AvalonDockTest.csproj
source/AutomationTest/AvalonDockTest/CollectionResetTest.cs
source/AutomationTest/AvalonDockTest/CustomObservableCollection.cs
source/AutomationTest/AvalonDockTest/LayoutAnchorableFloatingWindowControlTest.cs
source/AutomationTest/AvalonDockTest/LayoutAnchorableTest.cs
source/AutomationTest/AvalonDockTest/Properties/AssemblyInfo.cs
source/AutomationTest/AvalonDockTest/Views/CollectionResetTestWindow.xaml
source/AutomationTest/AvalonDockTest/Views/CollectionResetTestWindow.xaml.cs
source/AutomationTest/AvalonDockTest/packages.config
source/AvalonDock.sln
source/CaliburnDockTestApp/App.xaml
source/CaliburnDockTestApp/App.xaml.cs
source/CaliburnDockTestApp/AssemblyInfo.cs
source/CaliburnDockTestApp/Bootstrapper.cs
source/CaliburnDockTestApp/CaliburnDockTestApp.csproj
source/CaliburnDockTestApp/CaliburnLogger.cs
source/CaliburnDockTestApp/RelayCommand.cs
source/CaliburnDockTestApp/ViewModels/MainWindowViewModel.cs
source/CaliburnDockTestApp/ViewModels/TestViewModel.cs
source/CaliburnDockTestApp/ViewModels/ViewModelBase.cs
source/CaliburnDockTestApp/Views/MainWindowView.xaml
source/CaliburnDockTestApp/Views/MainWindowView.xaml.cs
source/CaliburnDockTestApp/Views/TestView.xaml
source/CaliburnDockTestApp/Views/TestView.xaml.cs
source/Components/AvalonDock/DockingManager.cs
source/Components/AvalonDock/ReferenceEqualityComparer.cs

This is the fix for #184 where the previous handler assumed the collection was cleared when the [`NotifyCollectionChangedAction.Reset`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedaction) action was received. The new handler iterates through the collection to find which items were removed and then only removes those items.
I added a test for the `Reset` handling in the AutomationTest `AvalonDockTest` project. It creates several `Anchorables` and `Documents` and uses a `CustomObservableCollection` that raises the `Reset` notification. I also modified that project (`AvalonDockTest`) to the new `csproj` format because the reference to `AvalonDock` since it had the new file format. There was an issue with the Apartment STA, so I referenced …

Fix ObservableCollection Reset notification handling

---

source/Components/AvalonDock/Layout/LayoutContent.cs

Hi Dirk, that's first of series of small and hopefully safe PRs that I plan to do for changes in our fork to synchronize with main.
In this one we raise PropertyChanged for IsFloating property of LayoutContent which is read-only and indirectly changed when layout element is made floating or docked back to main window.
In our project there are places where we have bindings to IsFloating and they don't work as expected due to notifications not being sent.

Raise PropertyChanged notification when LayoutContent.IsFloating changes

---

source/Components/AvalonDock/Controls/LayoutGridControl.cs

With certain layouts (produced by our software) undocking an anchorable leads to following:
> System.ArgumentOutOfRangeException
>   HResult=0x80131502
>   Message=Specified argument was out of the range of valid values.
> Parameter name: index
>   Source=PresentationCore
>   StackTrace:
>    at System.Windows.Media.VisualCollection.get_Item(Int32 index)
>    at System.Windows.Controls.UIElementCollection.get_Item(Int32 index)
>    at AvalonDock.Controls.LayoutGridControl`1.UpdateRowColDefinitions() in C:\SOURCE\Tests\AvalonDock\Dirkster99\source\Components\AvalonDock\Controls\LayoutGridControl.cs:line 255
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
>     AvalonDock.Controls.LayoutGridControl<T>.UpdateRowColDefinitions() in LayoutGridControl.cs
>

Added additional check in UpdateRowColDefinitions to avoid exception.

---

source/Components/AvalonDock.Themes.VS2013/Themes/Generic.xaml

Local style is created and is applied only to MenuItemEx by default.
This change is regarding #191

Default MenuItem style not changed by VS2013 Theme

---

source/Components/AvalonDock/Layout/LayoutDocument.cs

Hi Dirk, here's my alternative idea for fixing #196. Adding CanHide always returning false to LayoutDocument seems safe change. That would also avoid Binding warnings that would otherwise occur due to missing property in LayoutDocument:
`System.Windows.Data Warning: 40 : BindingExpression path error: 'CanHide' property not found on 'object' ''LayoutDocument' (HashCode=42353227)'. BindingExpression:Path=CanHide; DataItem='LayoutDocument' (HashCode=42353227); target element is 'LayoutDocumentTabItem' (Name=''); target property is 'NoTarget' (type 'Object')
`

Add to LayoutDocument CanHide property returning false

---

source/Components/AvalonDock/DockingManager.cs

Fix issue where the ActiveContent binding doesn't update two ways when removing a document.

---

source/Components/AvalonDock/Controls/DocumentPaneDropTarget.cs

When dropping a DoucumentPane onto another DoucumentPane, the process freezes under certain condition
Occurs in the following situations
1. Launch TestApp
2. Document1 drop to target Right
3. Document1 drop to target Top
4. Document2 drop to target Document1
5. freeze
It seems to be an old problem, and that part has been fixed

Fixed a bug that freezed when changing DocumentPane Orientation

---

source/Components/AvalonDock/Controls/LayoutDocumentPaneControl.cs

To reproduce the issue:
1. Open the MVVM example, select the "Aero" theme (makes the steps in the ui easier)
2. Open 2 documents. the 2 documents are displayed in 2 distinct tabs (correct)
3. Change documents by clicking on the tab header, outside the text label (with aero theme, click on the spline on the left part of the tab). The displayed tab changes (correct), the lower toolwindow (display of the document properties) does not change (incorrect).
The lower toolwindow is bound on the ActiveDocument (defined by the "IsActive" flag), the displayed tab is based on the "IsSelected" flag.
Fix: re-integrated code from older version (removed in rev 49274532)
Resolves #163

Issue 163: IsSelected vs IsActive behavior changed from 3.x to 4.1/4.2

---

source/Components/AvalonDock/Controls/LayoutFloatingWindowControl.cs
source/TestApp/MainWindow.xaml

Maximized floating windows sit under the task bar

---

source/Components/AvalonDock/DockingManager.cs

The list was filled to late. DockingManager_Loaded could occure again before the list of created elements was filled #254

Don't create FloatingWindows twice

---

source/AutomationTest/AvalonDockTest/AvalonDockTest.csproj
source/CaliburnDockTestApp/CaliburnDockTestApp.csproj
source/Components/AvalonDock.Themes.Aero/AvalonDock.Themes.Aero.csproj
source/Components/AvalonDock.Themes.Expression/AvalonDock.Themes.Expression.csproj
source/Components/AvalonDock.Themes.Metro/AvalonDock.Themes.Metro.csproj
source/Components/AvalonDock.Themes.VS2010/AvalonDock.Themes.VS2010.csproj
source/Components/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.csproj
source/Components/AvalonDock/AvalonDock.csproj
source/MLibTest/MLibTest/MLibTest.csproj
source/MLibTest/MLibTest_Components/ServiceLocator/ServiceLocator.csproj
source/MLibTest/MLibTest_Components/Settings/SettingsModel/SettingsModel.csproj
source/MVVMTestApp/MVVMTestApp.csproj
source/TestApp/TestApp.csproj
source/WinFormsTestApp/WinFormsTestApp.csproj

This PR aims to migrate Dirkster.AvalonDock from targetting netcoreapp3.0 to net5.0 and net5.0-windows.
Fixes #213
The first step of changing target framework is done and everything seems to work. However there are lots of warnings and I have not yet checked if they are present in netcoreapp3.0. We might want to do more maintenance work. 
Let me know what you think when you have tried it out.

Migrate from netcoreapp3.0 to net5.0-windows

---

source/Components/AvalonDock/DockingManager.cs
source/Components/AvalonDock/Themes/generic.xaml

I ran into a problem where my tests were failing when updating to version 4.30.0 or later. I got an exception in `DockingManager.OnContextMenuPropertyChanged()`. It was introduced as part of 
#170 to solve a problem with the context menu.
[Here](https://github.com/Dirkster99/AvalonDock/commit/64b30e7c548a5d764dbdfc93eafd529aa769b527#diff-3d578478402a239252f3c6d75949ba698d45443ddadb187191f58fc1249bb9b6R1802) is a link to the specific change (you will have to expand the diff of DockingManager to see the row).
My problem is that I'm running tests with the DockingManager in XUnit with [StaFact](https://github.com/AArnott/Xunit.StaFact). StaFact makes sure that the tests run on on STA thread. But it doesn't guarantee that all tests within a class runs on the _same_ STA thread. Hence `d` will …

Fixing problems with tests running with XUnit StaFact

---

source/Components/AvalonDock/Controls/LayoutAnchorControl.cs
source/Components/AvalonDock/Layout/LayoutContent.cs
source/TestApp/MainWindow.xaml

For our use case we would like the option to not auto-show a LayoutAnchorable
on mouse over (via mouse enter). This adds a new property to provide an option
to disable the auto-show behavior. Serialization support included.
Is there a better way to handle this?

Optional show hidden LayoutAnchorable on hover

---

source/Components/AvalonDock/Properties/Resources.pt.resx

Some of our Portuguese users reported that they were seeing the strings in English, instead of Portuguese.
It appears that the branch has marked the Portuguese resource strings as 'pt-BR', which would be fine if there was a also a file for 'pt' to use as the fallback for Portuguese.  Since we don't have another resource file for Portuguese, we would like to move the Brazilian Portuguese translations to be the default for Portuguese.

Rename pt-BR to pt

---

source/Components/AvalonDock.Themes.VS2013/Themes/Generic.xaml

Fix Mismatched ResourceKey on VS2013 Theme

---

source/Components/AvalonDock/Controls/LayoutGridControl.cs
source/Components/AvalonDock/DockingManager.cs

**Summary**
This change adds support for specifying a custom style to be used for the generated vertical and horizontal grid resizers.
**Description of the Problem**
Although it is possible to apply a default style to all instances of the LayoutGridResizerControl, our styling team had the desire to apply a custom style to only the vertical style.  This was not currently possible, since there were no existing hooks for setting the style for this control. 
**Proposed Solution**
This code adds properties to allow custom styles to be specified for either the vertical or horizontal LayoutGridResizerControl that is created.  If the property is not set, the code will behave as before.

Support custom styles for LayoutGridResizerControl

---

source/Components/AvalonDock/Controls/LayoutFloatingWindowControl.cs
source/Components/AvalonDock/DockingManager.cs

The current behavior treats all the windows as a group.  Minimizing the main window will cause all the floating windows to be minimized.  Also, if you minimize a floating window, it is minimized but then is immediately restored.
Our users requested that the they have the ability to minimize the windows independently.  This is because they may need to minimize a single window that is in the way of another window, but they do not necessarily want to minimize all the other windows for the app.
In order to support this, this change adds 2 properties to the `LayoutFloatingWindowControl`:
- `AllowMinimize` which determines whether a floating window can be minimized.  Setting this to 'true' enables the ability to minimize the floating window while leaving the main window as it is.
- …

Support minimizing floating windows independently of main window

---

source/Components/AvalonDock/Controls/LayoutDocumentFloatingWindowControl.cs
source/Components/AvalonDock/Win32Helper.cs

This is a fix for Issue #287 
When configured to display floating windows in the taskbar, the close button in the taskbar does not function.  This is because it calls the Window.Close method directly and bypasses the close logic that is used elsewhere in the application.
This fix watches for the close event and forces it to use the normal logic.

Fix close from taskbar for floating window

---

source/Components/AvalonDock/Controls/LayoutFloatingWindowControl.cs

Fixed #281 
Location: LayoutFloatingWindowControl.cs
The issue was fixed by specifying the UI Automation name for the root visual in the host control. This causes the GenericRootAutomationPeer to default to getting that value instead of trying to use the Win32 API to get the value of a (possibly disposed) window.
I was not able to figure out how to solve the root cause which is caused by GCHandles to the Border (RootVisual) still hanging around after the window is closed. Since the UI Automation uses WeakReferences to check which elements are still alive, this issue could also be solved by clearing all references to the RootVisual object, but that is easier said than done.
I was not able to reproduce the issue with a simple UI that I can share. Probably this issue is caused by some …

281 floating window host: UI automation name

---

source/Components/AvalonDock/Controls/NavigatorWindow.cs

See https://github.com/icsharpcode/ILSpy/issues/2577.
The issue is that NavigatorWindow expects at least two documents and/or anchorables, otherwise it will not focus the listbox(es) correctly and further not allow the user to switch between documents/anchorables. The only way to exit the window is by using a mouse. However, some people may not be able to use a mouse or might use tools (e.g. Screen Readers, Voice Commands) that work solely by emulating key presses.

Fix NavigatorWindow not working if there is only one document

---

source/Components/AvalonDock/Layout/LayoutAnchorableFloatingWindow.cs
source/Components/AvalonDock/Layout/LayoutDocumentFloatingWindow.cs
source/Components/AvalonDock/Layout/LayoutFloatingWindow.cs
source/Components/AvalonDock/Layout/LayoutGroup.cs
source/Components/AvalonDock/Layout/LayoutRoot.cs
source/Components/AvalonDock/Layout/Serialization/LayoutSerializer.cs
source/Components/AvalonDock/Layout/Serialization/XmlLayoutSerializer.cs

Changed serialization because it did not work as intended. While making a small change to functionality tidied the code a little bit more.

Serialization

---

source/Components/AvalonDock/Controls/LayoutDocumentTabItem.cs

Just added a nullcheck before invoking the close command. Also added braces to the if statement for clarity.

Aded LayoutItem null check when processing mouseMiddleClickButton

---

source/Components/AvalonDock/Controls/DragService.cs
source/Components/AvalonDock/Controls/DropArea.cs
source/Components/AvalonDock/Controls/DropTarget.cs
source/Components/AvalonDock/Controls/IDropTarget.cs
source/Components/AvalonDock/Controls/IOverlayWindowHost.cs
source/Components/AvalonDock/Controls/LayoutAnchorableFloatingWindowControl.cs
source/Components/AvalonDock/Controls/LayoutDocumentFloatingWindowControl.cs
source/Components/AvalonDock/Controls/LayoutFloatingWindowControl.cs
source/Components/AvalonDock/Controls/LayoutGridControl.cs
source/Components/AvalonDock/DockingManager.cs

https://github.com/Dirkster99/AvalonDock/issues/321
This now covers all cases that I can find. There are still issues if the application does not declare per-monitor DPI awareness and the docking host window is split over two monitors with different DPIs, but these existed already, and I don't think it is possible to solve that sort of issue *without* being per monitor DPI aware.
A number of changes are needed, largely taking into account the fact that a floating window can have a different DPI to the main docking window in a per-monitor DPI aware application:
* The drag service needs to work in raw screen co-ordinates and let each window it hit tests do its own conversion into DPI scaled co-ordinates, since the conversion may be different on a per window basis. I renamed HitTest() to …

A more complete fix to per-monitor DPI issues

---

source/Components/AvalonDock/Controls/DropTarget.cs

currentActiveContent can be null and will throw an exception

NullCheck for currentActiveContent

---

source/Components/AvalonDock/Themes/generic.xaml

I've added a new style without a key based on the existing style. This has the benefits of keeping the style with the key so that other people can create their own styles based on this, but it also applies this style by default. I've tested this in the test app and it worked fine for me.

Fixes #309 Anchorable Header not visible in generic theme

---

source/Components/AvalonDock/Layout/LayoutRoot.cs

i.e. in Microsoft.Practices.Unity, Version=2.1.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
this comes up after migration from xceed AvalonDock version 2.
Additional to that I prioritize the AvalonDock assembly, because this is the most used.

fix crash if some assembly not allow GetTypes()

---

source/Components/AvalonDock/Controls/LayoutAutoHideWindowControl.cs

In this PR, we add logic to detect when the `DockingManager` is a descendent of one more `Viewbox` controls. We then adjust the `LayoutTransform` of the `LayoutAutoHideWindowControl` and its child as necessary to make the child have the correct zoom and behave as if the window were a descendent of the `DockingManager`. Additionally, we make a small fix to dragging the window to resize it.
We update the `LayoutTransform` when the `LayoutAutoHideWindowControl` is shown and when any of its descendents' `Viewbox`es or their direct children's size changes.

Fixes #362 DockingManager with a Viewbox ancestor does not properly render auto-hidden LayoutAnchorables

---

source/Components/AvalonDock/Controls/LayoutDocumentTabItem.cs
source/Components/AvalonDock/Controls/LayoutFloatingWindowControl.cs

Some time ago, i created an issue #306 where i mentions that method StartDraggingFloatingWindow do not sync mouse position with newly created window.
After some attempts i found out, that when i add CaptureMouse() to methods OnMouseLeftButtonDown (LayoutDocumentTabItem.cs) and AttachDrag (LayoutFloatingWindowControls.cs) it solves my issue

Fix for #306 StartDraggingFloatingWindow

---

source/Components/AvalonDock/Controls/LayoutAnchorableFloatingWindowControl.cs
source/Components/AvalonDock/Controls/LayoutDocumentFloatingWindowControl.cs
source/Components/AvalonDock/DockingManager.cs

This is a proposed fix for https://github.com/Dirkster99/AvalonDock/issues/349.
The ownership of the OverlayWindow was changed in https://github.com/Dirkster99/AvalonDock/pull/326. This works great when the overlay window is a child of the main window. However, if the floating window being dragged isn't also a child of the main window (because OwnedByDockingManagerWindow is set to false to allow the parent window to be minimized independently of floating windows), this causes the floating window to be moved behind the main window. 
This issue is resolved by not setting the Owner of the OverlayWindow. These changes clear the owner only in the case where the OwnedByDockingManagerWindow is set to false for the window. Otherwise, it maintains the existing behavior.

Fix window going behind main window when dragging

---

source/Components/AvalonDock/Controls/LayoutFloatingWindowControl.cs

If a childwindow ist opened and closed and this control is closed the main window is minimized. The workaround with setting the owner to null is not working, therefor Activate is used https://stackoverflow.com/questions/19156373/closing-child-window-minimizes-parent

Prevents a known bug in WPF

---

source/Components/AvalonDock/Controls/LayoutAnchorableFloatingWindowControl.cs
source/Components/AvalonDock/Controls/LayoutDocumentFloatingWindowControl.cs

Null exception occurs when WindowChrome is not from AvalonDock
https://user-images.githubusercontent.com/62750690/199029350-1dbf5090-7680-4899-b8ad-5bcc54d8fc86.mp4

Add Null check for GetWindowChrome

---

source/Components/AvalonDock/Controls/DragService.cs
source/Components/AvalonDock/Controls/LayoutAnchorableFloatingWindowControl.cs
source/Components/AvalonDock/Controls/LayoutDocumentFloatingWindowControl.cs
source/Components/AvalonDock/Controls/LayoutFloatingWindowControl.cs
source/Components/AvalonDock/DockingManager.cs
source/Components/AvalonDock/Win32Helper.cs

See: pull https://github.com/Dirkster99/AvalonDock/pull/350  | issue https://github.com/Dirkster99/AvalonDock/issues/349
Before:
this = FloatingWindow, GetWindow(this) = self.
but, where DockingManagerWindow ?🤣
Now:
Get DockingManagerWindow correctly

Fix the get owner DockingManagerWindow and Update drag and drop

---

source/Components/AvalonDock/DockingManager.cs
source/Components/AvalonDock/LayoutFloatingWindowControlClosedEventArgs.cs
source/Components/AvalonDock/LayoutFloatingWindowControlCreatedEventArgs.cs

#386
Add ```LayoutFloatingWindowControlCreated``` and ```LayoutFloatingWindowControlClosed``` events to DockerManger

add open/close LayoutFlayoutingWindowsControl events

---

source/Components/AvalonDock/Layout/LayoutAnchorableFloatingWindow.cs
source/Components/AvalonDock/Layout/LayoutDocumentFloatingWindow.cs
source/Components/AvalonDock/Layout/LayoutFloatingWindow.cs
source/Components/AvalonDock/Layout/LayoutGroup.cs
source/Components/AvalonDock/Layout/LayoutRoot.cs
source/Components/AvalonDock/Layout/Serialization/XmlLayoutSerializer.cs
source/Components/AvalonDock/XmlSerializersCache.cs

Implemented 2nd option I suggested in #356

Add XmlSerializer cache to fix memory leaks.

---

source/Components/AvalonDock/DockingManager.cs
source/Components/AvalonDock/Layout/LayoutElement.cs
source/Components/AvalonDock/Layout/Serialization/LayoutSerializer.cs

Recently I mentioned that `LayoutElement._root` doesn't have correct value after deserialization. When we deserialize layout from xml enclosing element is not finished with yet and therefore doesn't have correct parent yet.
This state prevents `LayoutRoot.ElementRemoved` from being called on close, which leads to skipped call to `DockingManager.CollectLayoutItemsDeleted`. 
Also I mentioned that documents closed via deletion from `DockingManager.DocumentsSource` did not have their `Content` property set to null. Though we do it for `AnchorablesSource` and in `ExecuteCloseCommand`, so I added it.

Fix deserialized layout document close.

---

source/Components/AvalonDock/Layout/LayoutAnchorablePane.cs
source/Components/AvalonDock/Layout/LayoutDocumentPane.cs

Fixes #201 
I kept the original `SetNextSelectedIndex` method since it's still called in `LayoutDocumentControl` and `LayoutAnchorableControl`.

Restore previously activated document after closing active document

---

source/Components/AvalonDock/Controls/LayoutAnchorableFloatingWindowControl.cs
source/Components/AvalonDock/Controls/LayoutDocumentFloatingWindowControl.cs
source/Components/AvalonDock/Controls/LayoutFloatingWindowControl.cs

Fix https://github.com/Dirkster99/AvalonDock/issues/408

Improved activation of floating Windows

---

source/AutomationTest/AvalonDockTest/AnchorablePaneTest.cs
source/Components/AvalonDock/AnchorableClosedEventArgs.cs
source/Components/AvalonDock/AnchorableClosingEventArgs.cs
source/Components/AvalonDock/AnchorableHiddenEventArgs.cs
source/Components/AvalonDock/AnchorableHidingEventArgs.cs
source/Components/AvalonDock/Controls/LayoutAnchorableItem.cs
source/Components/AvalonDock/DockingManager.cs
source/Components/AvalonDock/Layout/LayoutAnchorable.cs
source/Components/AvalonDock/Layout/Serialization/LayoutSerializer.cs

This change adds close and hide events to DockingManager for anchorables. This brings anchorables inline with documents (LayoutDocument) as documents already have this functionality in DockingManager.
The reason for this change is so I can use a custom PrismLibrary region adapter for DockingManager. A PrismLibrary region adapter needs to track when controls are visibly removed from a parent, which in this case is DockingManager. Sample region adapters for other parent panels can be found [in this repo](https://github.com/PrismLibrary/Prism/tree/master/src/Wpf/Prism.Wpf/Regions).
This code is a port from a custom version of the old AvalonDock that I have been using with PrismLibrary for many years. I have added unit tests for the new functionality.

Add anchorable hide and close notifications to DockingManager

---

source/Components/AvalonDock/Controls/DragService.cs

In some special cases, the floating window is still displayed above the overlay window.

Fix a issue where the dragged window still appeared above the overlay window

---

source/Components/AvalonDock.Themes.Aero/Theme.xaml
source/Components/AvalonDock.Themes.Expression/Theme.xaml
source/Components/AvalonDock.Themes.Metro/Theme.xaml
source/Components/AvalonDock.Themes.VS2010/Theme.xaml
source/Components/AvalonDock.Themes.VS2013/Themes/Generic.xaml
source/Components/AvalonDock/Themes/generic.xaml

https://github.com/Dirkster99/AvalonDock/blob/1d4d30d9969236c3717b8a6f430809a230ff671a/source/Components/AvalonDock/Themes/generic.xaml#L393-L395
(Converter)
(DataTriggers)
Binding errors are avoided by using data triggers instead of converter

Fix the binding error in AnchorGroupTemplate

---

source/Components/AvalonDock/Controls/LayoutAnchorSideControl.cs

Fix https://github.com/Dirkster99/AvalonDock/issues/402

When apply new template, add back collection change event handler

---

source/Components/AvalonDock/Controls/LayoutFloatingWindowControl.cs

This pull request should fix the issue #226 of owned/maximized floating windows (LayoutFloatingWindowControl) not restoring to maximized state when the owner (DockingManager) window is restored from being minimized.

Issue #226: Restore floating windows to maximized state

---

source/Components/AvalonDock/DockingManager.cs

It doesn't make sense for our use case, and there's no other way to turn it off.

Add DockingManager.ShowNavigator

---

source/Components/AvalonDock/Controls/DocumentPaneDropTarget.cs

Dragging a floating document into the top or bottom of another document that is in a horizontal layout causes an unexpected change in the layout group. This only happens when using AllowMixedOrientation as the placement is not allowed otherwise.
As you can see in this example, a tab was dragged from the right side onto the bottom of another document:
Which causes the whole layout to change:
With the changes from this pull request the document is placed in the expected position:

Fix unwanted group orientation change when using mixed orientation

---

source/Components/AvalonDock/Controls/LayoutAnchorableFloatingWindowControl.cs
source/Components/AvalonDock/Controls/LayoutDocumentFloatingWindowControl.cs
source/Components/AvalonDock/Controls/TransformExtentions.cs

The following exception has been reported:
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Full Exception:
bei AvalonDock.Controls.TransformExtensions.TransformToDeviceDPI(Visual visual, Point pt)
bei AvalonDock.DockingManager.AvalonDock.Controls.IOverlayWindowHost.HitTestScreen(Point dragPoint)
bei AvalonDock.Controls.DragService.<>c__DisplayClass9_0.<UpdateMouseLocation>b__0(IOverlayWindowHost oh)
bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
bei AvalonDock.Controls.DragService.UpdateMouseLocation(Point dragPosition)
bei AvalonDock.Controls.DragService.Drop(Point dropLocation, Boolean& dropHandled)
bei AvalonDock.Controls.LayoutFloatingWindowControl.FilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& …

NullCheck for DragPoint

---

source/Components/AvalonDock/DockingManager.cs

When there's a single document in a floating window like this:
..and you close that document, the next active document becomes Document 2 which changes the selected document in the other pane. Expected behavior is that Document 1 remains the selected document and becomes active.
The implementation uses the global index of the closing document and tries to set the document at index - 1 to active, regardless of the containers.

Changed how the next active document is picked on document close.
