- source/Components/Xceed.Wpf.AvalonDock/Themes/generic.xaml
https://github.com/xceedsoftware/wpftoolkit/issues/1203
> Fixed height of titles of floating windows #1203

- source/Components/Xceed.Wpf.AvalonDock/AssemblyVersionInfo.cs
- source/Components/Xceed.Wpf.AvalonDock/Themes/generic.xaml
AvalonDock PanesTemplateSelector is ignored
https://github.com/xceedsoftware/wpftoolkit/issues/1440
> Fixed Issue #1440

- .gitignore
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/AnchorablePaneTest.cs
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/Properties/AssemblyInfo.cs
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/TestApp.xaml
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/TestApp.xaml.cs
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/TestHelpers/AutomationTestBase.cs
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/TestHelpers/Extensions.cs
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/TestHelpers/SwitchContextToUiThreadAwaiter.cs
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/TestHelpers/TestHost.cs
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/TestHelpers/WindowHelpers.cs
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/Testsettings.runsettings
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/Views/AnchorablePaneTestWindow.xaml
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/Views/AnchorablePaneTestWindow.xaml.cs
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/Xceed.Wpf.AvalonDock.Test.csproj
- source/AutomationTest/Xceed.Wpf.AvalonDock.Test/packages.config
- source/AvalonDock.sln
- source/Components/Xceed.Wpf.AvalonDock/Controls/FocusElementManager.cs
I wrote some test code and the inspiration came from MahApps.Metro: https://github.com/MahApps/MahApps.Metro/tree/develop/src/Mahapps.Metro.Tests.
> Try to verify the updated function by Unit test.

- source/Components/Xceed.Wpf.AvalonDock/DockingManager.cs
- source/MLibTest/MLibTest/Demos/LayoutInitializer.cs
https://github.com/xceedsoftware/wpftoolkit/issues/1460
https://github.com/Dirkster99/AvalonDock/issues/18
> Fix for Issue #18

- source/Components/Xceed.Wpf.AvalonDock/DockingManager.cs
- source/Components/Xceed.Wpf.AvalonDock/Layout/Extentions.cs
- source/Components/Xceed.Wpf.AvalonDock/Layout/ILayoutElementForFloatingWindowExtension.cs
- source/Components/Xceed.Wpf.AvalonDock/Xceed.Wpf.AvalonDock.csproj
Solution to Issue #20
- Added Reload of floating LayoutAnchable when maximized on 2nd screen
- Added repositioning of floating LayoutAnchable when:
- 2nd Monitor is not available or
- changed resolution puts floating LayoutAnchable out of bounds
> 2nd monitor support

- source/Components/Xceed.Wpf.AvalonDock.Themes.VS2013/Themes/Generic.xaml
Issue solved: Use localized resource instead of constant string in 2013 Theme
> Fix Issue #34

- source/Components/Xceed.Wpf.AvalonDock/Controls/FocusElementManager.cs
I recently tried to move from the Exceed version of AvalonDock to this one, using the nuget feed for v3.5.7.
But every time my app starts, as soon as anything inside AvalonDock gets focus I get the following error
```
Exception thrown: 'System.ComponentModel.Win32Exception' in WindowsBase.dll 
("Invalid window handle") Exception thrown: 'System.ComponentModel.Win32Exception' in
WindowsBase.dll ("Invalid window handle") 	
Managed Debugging Assistant 'CallbackOnCollectedDelegate' : 
'A callback was made on a garbage collected delegate of type 
'Xceed.Wpf.AvalonDock!Xceed.Wpf.AvalonDock.Win32Helper+HookProc::Invoke'. 
This may cause application crashes, corruption and data loss. When passing delegates to 
unmanaged code, they must be kept alive by the managed application until it is …
```
> Check if we are not on the UI thread before doing Dispatcher.Invoke

- source/Components/Xceed.Wpf.AvalonDock/Xceed.Wpf.AvalonDock.csproj
- source/MLibTest/MLibTest/App.xaml.cs
- source/MLibTest/MLibTest/Demos/ViewModels/AD/FileViewModel.cs
- source/MLibTest/MLibTest/Demos/ViewModels/Interfaces/IWorkSpaceViewModel.cs
- source/MLibTest/MLibTest/Demos/ViewModels/WorkSpaceViewModel.cs
- source/MLibTest/MLibTest/MLibTest.csproj
- source/MLibTest/MLibTest/MainWindow.xaml
- source/MLibTest/MLibTest/MainWindow.xaml.cs
- source/MLibTest/MLibTest/Models/LayoutLoadedEventArgs.cs
- source/MLibTest/MLibTest/Models/LayoutLoader.cs
- source/MLibTest/MLibTest/Models/LayoutLoaderResult.cs
Loading layout with background task in MLib Test
> Load layout async

- source/Components/Xceed.Wpf.AvalonDock.Themes.VS2013/BlueBrushs.xaml
- source/Components/Xceed.Wpf.AvalonDock.Themes.VS2013/DarkBrushs.xaml
- source/Components/Xceed.Wpf.AvalonDock.Themes.VS2013/LightBrushs.xaml
- source/Components/Xceed.Wpf.AvalonDock.Themes.VS2013/OverlayButtons.xaml
- source/Components/Xceed.Wpf.AvalonDock.Themes.VS2013/Themes/ResourceKeys.cs
Renamed DockingButtonForegroundArrowBrusKey to DockingButtonForegroundArrowBrushKey
> Fixed typo

- source/Components/Xceed.Wpf.AvalonDock/Controls/LayoutFloatingWindowControl.cs
- source/Components/Xceed.Wpf.AvalonDock/Layout/ILayoutElementForFloatingWindowExtension.cs
- source/Components/Xceed.Wpf.AvalonDock/Layout/ILayoutPositionableElement.cs
- source/Components/Xceed.Wpf.AvalonDock/Layout/LayoutContent.cs
- source/Components/Xceed.Wpf.AvalonDock/Layout/LayoutPositionableGroup.cs
See Issue #92 for details
https://github.com/Dirkster99/AvalonDock/issues/92
> #92 Always update floating properties

- source/Components/AvalonDock/Controls/LayoutGridControl.cs
- source/Components/AvalonDock/Layout/LayoutGroup.cs
Attempt to reduce quantity of SizeChanged events.
> Fix #101 and new fix for #81 with docked pane becomes not visible.

- source/Components/AvalonDock/Controls/LayoutPanelControl.cs
The ratio for panes is now kept. not overwritten.
> Fix for #118, keep pane ratio when restoring.

- source/Components/AvalonDock/Commands/RelayCommand.cs
- source/Components/AvalonDock/Controls/DragService.cs
- source/Components/AvalonDock/Controls/DropArea.cs
- source/Components/AvalonDock/Controls/DropTargetType.cs
- source/Components/AvalonDock/Controls/IDropTarget.cs
- source/Components/AvalonDock/Controls/IOverlayWindow.cs
- source/Components/AvalonDock/Controls/IOverlayWindowHost.cs
- source/Components/AvalonDock/Controls/LayoutAnchorableFloatingWindowControl.cs
- source/Components/AvalonDock/DockingManager.cs
Updated documentation.
Applied codestyle to dependency properties.
Reduced empty lines, compacted code.
> Updated documentation.

- source/Components/AvalonDock/Controls/DocumentPaneDropTarget.cs
- source/TestApp/TestUserControl.xaml
Fix for issue [138](https://github.com/Dirkster99/AvalonDock/issues/138)
Fix typo
> Fix for issue 138

- source/Components/AvalonDock/DockingManager.cs
I made a simplified fix to the code I put into the original issue chain a "https://github.com/Dirkster99/AvalonDock/issues/194 App doesn't close after LayoutAnchorable AutoHide and docking it again".
Not sure how you do regressions or unit tests but it doesn't hang on exit anymore.
> Bug fix for issue #194 App doesn't close after LayoutAnchorable AutoHide and docking it again

- source/Components/AvalonDock/DockingManager.cs
Fixes  Dirkster99/AvalonDock#210
> Do not dock tools in LayoutDocumentPaneGroup if configuration does allow that

- source/Components/AvalonDock/Controls/LayoutAutoHideWindowControl.cs
- source/Components/AvalonDock/Controls/LayoutGridControl.cs
> Fix issue with default window style and resizer window host #221

- source/Components/AvalonDock/Controls/AnchorablePaneTitle.cs
- source/Components/AvalonDock/Controls/LayoutAnchorableControl.cs
- source/Components/AvalonDock/Controls/LayoutDocumentControl.cs
> Fixed NullReferenceException when Root is null

- source/Components/AvalonDock/Controls/DocumentPaneDropTarget.cs
I'm sorry for the trouble. 
I fixed the problem in the mentioned MLib.
The problem was caused by empty DocumentPaneGroup;
> ensure DocumentPaneGroup (fix crash when documentpane on layoutGroup)

- source/Components/AvalonDock/Controls/DropDownControlArea.cs
Fixes https://github.com/Dirkster99/AvalonDock/issues/244.
> Fix right click context menu bug

- source/Components/AvalonDock/Controls/LayoutDocumentPaneControl.cs
Fix: re-integrated code from older version (removed in rev 4927453)
See Issue #163 for details
> Issue 163: IsSelected vs IsActive behavior changed from 3.x to 4.1/4.2

- source/Components/AvalonDock/Themes/generic.xaml
I wanted to override this from my project, but I don't think I can do this unless a key is set here. If I'm mistaken let me know.
> Adding a key for AnchorablePaneTitle

- source/Components/AvalonDock/Layout/LayoutRoot.cs
> Keep ActiveContent when switching RootPanel

- source/Components/AvalonDock/Controls/Shell/WindowChromeWorker.cs
This fix resolve the bug #345 and simplifies the refresh of the non client area
> #345 fix refresh when moving floating windows

- source/Components/AvalonDock/Controls/LayoutAutoHideWindowControl.cs
similiar to https://github.com/Dirkster99/AvalonDock/pull/291/commits
as proposed in https://github.com/Dirkster99/AvalonDock/issues/344
> LayoutAutoHideWindowControl: UI automation name

- source/Components/AvalonDock/Controls/LayoutGridControl.cs
> set ResizeOverlay's owner always null

- source/Components/AvalonDock/Controls/DocumentPaneTabPanel.cs
> remove unused variable from DocumentPaneTabPanel

- source/Components/AvalonDock/Controls/LayoutDocumentFloatingWindowControl.cs
Improvements for https://github.com/Dirkster99/AvalonDock/pull/410 ...
There was some oversight in the previous commit... (I'm not quite used to using GitHub yet)
But I will carefully review and commit the code in the future❤️
> Improved and fix floating window activation and activation pane

- source/Components/AvalonDock/Themes/generic.xaml
[Issue #422](https://github.com/Dirkster99/AvalonDock/issues/422)
> issue #422

- source/Components/AvalonDock/DockingManager.cs
> Fix floating windows still created twice
